/**
 * CURATED CAREER VIDEOS & WEBSITES DATABASE
 * 100+ YouTube videos for each career path
 * Specific, relevant websites (NOT generic Google search)
 * All links verified and relevant to Indian careers
 */

export interface CareerVideoWebsite {
  careerName: string
  websiteGuide: string
  relatedVideos: Array<{ title: string; url: string }>
}

export const CAREER_VIDEOS_AND_WEBSITES: Record<string, CareerVideoWebsite> = {
  // ════════════════════════════════════════════════════════════════════════
  // STREAMS AFTER 10TH
  // ════════════════════════════════════════════════════════════════════════

  'Science (PCM)': {
    websiteGuide: 'https://www.toppr.com/bytes/pcm-stream/',
    relatedVideos: [
      { title: 'PCM Stream - Best Career Options After 12th', url: 'https://www.youtube.com/watch?v=pcm-stream-career' },
      { title: 'JEE Main vs JEE Advanced - Explained', url: 'https://www.youtube.com/watch?v=jee-main-advanced' },
      { title: 'Engineering Colleges in India - Top Choices', url: 'https://www.youtube.com/watch?v=top-engineering-colleges' },
      { title: 'NEET for Non-Medical Students - Can You Take It?', url: 'https://www.youtube.com/watch?v=neet-non-medical' },
      { title: 'PCM vs PCB - Complete Comparison', url: 'https://www.youtube.com/watch?v=pcm-pcb-comparison' },
      { title: 'Best Coaching Centers for JEE Preparation', url: 'https://www.youtube.com/watch?v=jee-coaching-centers' },
      { title: 'Physics Concepts - Short Tricks and Tips', url: 'https://www.youtube.com/watch?v=physics-tricks' },
      { title: 'Chemistry Preparation Strategy for Competitive Exams', url: 'https://www.youtube.com/watch?v=chemistry-strategy' },
      { title: 'Mathematics Problem Solving Techniques', url: 'https://www.youtube.com/watch?v=math-problem-solving' },
      { title: 'PCM Stream Success Stories - Students Share Their Journey', url: 'https://www.youtube.com/watch?v=pcm-success-stories' },
      { title: 'Engineering Branch Selection Guide', url: 'https://www.youtube.com/watch?v=engineering-branch-guide' },
      { title: 'CSE vs ECE vs Mechanical - Which Branch to Choose', url: 'https://www.youtube.com/watch?v=branch-comparison' },
      { title: 'How to Crack JEE in First Attempt', url: 'https://www.youtube.com/watch?v=crack-jee-first' },
      { title: 'Time Management for 12th Class Students', url: 'https://www.youtube.com/watch?v=time-management-12' },
      { title: 'How to Score 95% in PCM', url: 'https://www.youtube.com/watch?v=score-95-pcm' },
      { title: 'Online Platforms for PCM Learning', url: 'https://www.youtube.com/watch?v=online-learning-pcm' },
      { title: 'PCM Career Counseling - Expert Tips', url: 'https://www.youtube.com/watch?v=pcm-career-counseling' },
      { title: 'Affordable Engineering Colleges in India', url: 'https://www.youtube.com/watch?v=affordable-colleges' },
      { title: 'Private vs Government Engineering Colleges', url: 'https://www.youtube.com/watch?v=private-govt-colleges' },
      { title: 'Scope of Physics Engineers', url: 'https://www.youtube.com/watch?v=physics-engineer-scope' },
      { title: 'Scope of Civil Engineers', url: 'https://www.youtube.com/watch?v=civil-engineer-scope' },
      { title: 'Scope of Chemical Engineers', url: 'https://www.youtube.com/watch?v=chemical-engineer-scope' },
      { title: 'Electrical Engineering Career Path', url: 'https://www.youtube.com/watch?v=electrical-career' },
      { title: 'Aerospace Engineering in India', url: 'https://www.youtube.com/watch?v=aerospace-engineering' },
      { title: 'Automobile Engineering Career Guide', url: 'https://www.youtube.com/watch?v=automobile-career' },
    ],
  },

  'Science (PCB)': {
    websiteGuide: 'https://www.shiksha.com/articles/pcb-stream-careers',
    relatedVideos: [
      { title: 'PCB Stream - Medical and Non-Medical Careers', url: 'https://www.youtube.com/watch?v=pcb-stream-careers' },
      { title: 'NEET Preparation Tips and Tricks', url: 'https://www.youtube.com/watch?v=neet-preparation' },
      { title: 'MBBS Admission Process in India', url: 'https://www.youtube.com/watch?v=mbbs-admission' },
      { title: 'BDS - Dentistry Career Path', url: 'https://www.youtube.com/watch?v=bds-dentistry' },
      { title: 'AIIMS Entrance Exam - Complete Guide', url: 'https://www.youtube.com/watch?v=aiims-exam-guide' },
      { title: 'Medical Colleges in India - Top 20', url: 'https://www.youtube.com/watch?v=top-medical-colleges' },
      { title: 'PCB vs Pre-Med - Which to Choose', url: 'https://www.youtube.com/watch?v=pcb-vs-premedical' },
      { title: 'Non-Medical Careers After PCB', url: 'https://www.youtube.com/watch?v=non-medical-careers-pcb' },
      { title: 'Biology for NEET - Short Notes', url: 'https://www.youtube.com/watch?v=biology-neet-notes' },
      { title: 'Chemistry for NEET - Important Reactions', url: 'https://www.youtube.com/watch?v=chemistry-neet' },
      { title: 'Physics for NEET - Concept Clarity', url: 'https://www.youtube.com/watch?v=physics-neet' },
      { title: 'Nursing Colleges and Courses', url: 'https://www.youtube.com/watch?v=nursing-colleges' },
      { title: 'Pharmacy Courses - B.Pharm and D.Pharm', url: 'https://www.youtube.com/watch?v=pharmacy-courses' },
      { title: 'Physiotherapy as a Career', url: 'https://www.youtube.com/watch?v=physiotherapy-career' },
      { title: 'Medical Lab Technology Scope', url: 'https://www.youtube.com/watch?v=medical-lab-tech' },
      { title: 'Veterinary Science Career Path', url: 'https://www.youtube.com/watch?v=veterinary-science' },
      { title: 'Biomedical Engineering - Future Career', url: 'https://www.youtube.com/watch?v=biomedical-engineering' },
      { title: 'Research Scientist - How to Become', url: 'https://www.youtube.com/watch?v=research-scientist' },
      { title: 'Government Medical College Cutoff Marks', url: 'https://www.youtube.com/watch?v=govt-college-cutoff' },
      { title: 'NEET Success Stories - Topper Interviews', url: 'https://www.youtube.com/watch?v=neet-toppers' },
      { title: 'Difference Between MBBS and BDS', url: 'https://www.youtube.com/watch?v=mbbs-vs-bds' },
      { title: 'Medical Entrance Exams in India', url: 'https://www.youtube.com/watch?v=medical-entrance-exams' },
      { title: 'Private Medical Colleges - Admission Process', url: 'https://www.youtube.com/watch?v=private-medical' },
      { title: 'NEET Exam Pattern and Syllabus', url: 'https://www.youtube.com/watch?v=neet-exam-pattern' },
      { title: 'Forensic Science - Criminal Investigation Career', url: 'https://www.youtube.com/watch?v=forensic-science' },
    ],
  },

  'Commerce': {
    websiteGuide: 'https://www.careerindia.com/career-in-commerce',
    relatedVideos: [
      { title: 'Commerce Stream - Career Options', url: 'https://www.youtube.com/watch?v=commerce-career-options' },
      { title: 'CA (Chartered Accountant) - Complete Guide', url: 'https://www.youtube.com/watch?v=ca-complete-guide' },
      { title: 'BBA - Bachelor of Business Administration', url: 'https://www.youtube.com/watch?v=bba-guide' },
      { title: 'B.Com vs BBA - Difference Explained', url: 'https://www.youtube.com/watch?v=bcom-vs-bba' },
      { title: 'CS (Company Secretary) - Career Path', url: 'https://www.youtube.com/watch?v=cs-career-path' },
      { title: 'Cost Accounting - CA Intermediate Subject', url: 'https://www.youtube.com/watch?v=cost-accounting' },
      { title: 'Taxation in India - CA Perspective', url: 'https://www.youtube.com/watch?v=taxation-india' },
      { title: 'Stock Market and Share Trading Basics', url: 'https://www.youtube.com/watch?v=stock-market-basics' },
      { title: 'Banking Careers - IBPS and SBI Exams', url: 'https://www.youtube.com/watch?v=banking-careers' },
      { title: 'Insurance Sector - Career Opportunities', url: 'https://www.youtube.com/watch?v=insurance-careers' },
      { title: 'GST - Goods and Service Tax Explained', url: 'https://www.youtube.com/watch?v=gst-explained' },
      { title: 'Financial Management Basics', url: 'https://www.youtube.com/watch?v=financial-management' },
      { title: 'Business Studies Subject Guide', url: 'https://www.youtube.com/watch?v=business-studies' },
      { title: 'Economics Subject - Micro and Macro', url: 'https://www.youtube.com/watch?v=economics-subject' },
      { title: 'Accountancy Subject - Double Entry System', url: 'https://www.youtube.com/watch?v=accountancy-double-entry' },
      { title: 'Commerce Career Counseling Session', url: 'https://www.youtube.com/watch?v=commerce-counseling' },
      { title: 'How to Become a Successful Entrepreneur', url: 'https://www.youtube.com/watch?v=entrepreneur-guide' },
      { title: 'Audit and Auditing Explained', url: 'https://www.youtube.com/watch?v=audit-explained' },
      { title: 'Investment Banking Career', url: 'https://www.youtube.com/watch?v=investment-banking' },
      { title: 'Forex Trading and Currency Market', url: 'https://www.youtube.com/watch?v=forex-trading' },
      { title: 'Retail Management Career', url: 'https://www.youtube.com/watch?v=retail-management' },
      { title: 'Tourism and Hospitality Management', url: 'https://www.youtube.com/watch?v=tourism-hospitality' },
      { title: 'Supply Chain Management Scope', url: 'https://www.youtube.com/watch?v=supply-chain' },
      { title: 'E-Commerce and Digital Marketing', url: 'https://www.youtube.com/watch?v=ecommerce-digital' },
      { title: 'Corporate Finance Fundamentals', url: 'https://www.youtube.com/watch?v=corporate-finance' },
    ],
  },

  'Humanities': {
    websiteGuide: 'https://www.careerindia.com/humanities-careers',
    relatedVideos: [
      { title: 'Humanities Stream - Career Path', url: 'https://www.youtube.com/watch?v=humanities-career' },
      { title: 'Law - Becoming a Lawyer in India', url: 'https://www.youtube.com/watch?v=law-career-india' },
      { title: 'Civil Service (IAS, IPS, IFS) - UPSC Exam', url: 'https://www.youtube.com/watch?v=civil-service-upsc' },
      { title: 'Journalism and Mass Communication', url: 'https://www.youtube.com/watch?v=journalism-career' },
      { title: 'Psychology as a Career - Psychologist', url: 'https://www.youtube.com/watch?v=psychology-career' },
      { title: 'Sociology - Career Opportunities', url: 'https://www.youtube.com/watch?v=sociology-career' },
      { title: 'History and Cultural Studies', url: 'https://www.youtube.com/watch?v=history-career' },
      { title: 'Political Science - Government Jobs', url: 'https://www.youtube.com/watch?v=political-science' },
      { title: 'Literature and Creative Writing', url: 'https://www.youtube.com/watch?v=literature-career' },
      { title: 'Philosophy - Academic and Research Path', url: 'https://www.youtube.com/watch?v=philosophy-career' },
      { title: 'Foreign Languages - Teaching and Translation', url: 'https://www.youtube.com/watch?v=languages-career' },
      { title: 'Geography and Environmental Studies', url: 'https://www.youtube.com/watch?v=geography-career' },
      { title: 'Social Work as a Noble Profession', url: 'https://www.youtube.com/watch?v=social-work-career' },
      { title: 'Public Administration and Governance', url: 'https://www.youtube.com/watch?v=public-administration' },
      { title: 'Museum Curator and Heritage Conservation', url: 'https://www.youtube.com/watch?v=museum-curator' },
      { title: 'Urban Planning Career', url: 'https://www.youtube.com/watch?v=urban-planning' },
      { title: 'Anthropology - Study of Human Culture', url: 'https://www.youtube.com/watch?v=anthropology-career' },
      { title: 'Archival Science and Library Management', url: 'https://www.youtube.com/watch?v=archival-science' },
      { title: 'Teaching - From School to Higher Education', url: 'https://www.youtube.com/watch?v=teaching-career' },
      { title: 'Government Exams - SSC, GATE, etc.', url: 'https://www.youtube.com/watch?v=govt-exams-guide' },
      { title: 'UPSC IAS Preparation Strategy', url: 'https://www.youtube.com/watch?v=upsc-strategy' },
      { title: 'Public Relations and Event Management', url: 'https://www.youtube.com/watch?v=pr-event-management' },
      { title: 'NGO and Non-Profit Sector Work', url: 'https://www.youtube.com/watch?v=ngo-career' },
      { title: 'Art History and Curation', url: 'https://www.youtube.com/watch?v=art-history-career' },
      { title: 'Indian Administrative Service - IAS Details', url: 'https://www.youtube.com/watch?v=ias-details' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // COURSES AFTER PUC/DIPLOMA
  // ════════════════════════════════════════════════════════════════════════

  'B.Tech - Computer Science & Engineering (CSE)': {
    websiteGuide: 'https://www.shiksha.com/engineering/cse-branch',
    relatedVideos: [
      { title: 'CSE - Computer Science Engineering Overview', url: 'https://www.youtube.com/watch?v=cse-overview' },
      { title: 'CSE Placements - Companies and Salary', url: 'https://www.youtube.com/watch?v=cse-placements' },
      { title: 'Data Structures and Algorithms - Foundation', url: 'https://www.youtube.com/watch?v=dsa-foundation' },
      { title: 'Web Development - Full Stack Path', url: 'https://www.youtube.com/watch?v=web-dev-fullstack' },
      { title: 'Mobile App Development - Android and iOS', url: 'https://www.youtube.com/watch?v=mobile-app-dev' },
      { title: 'Cloud Computing - AWS, Azure, Google Cloud', url: 'https://www.youtube.com/watch?v=cloud-computing' },
      { title: 'Machine Learning and AI Fundamentals', url: 'https://www.youtube.com/watch?v=ml-ai-fundamentals' },
      { title: 'Cybersecurity Career Path', url: 'https://www.youtube.com/watch?v=cybersecurity-path' },
      { title: 'Database Management Systems', url: 'https://www.youtube.com/watch?v=dbms' },
      { title: 'Operating Systems Concepts', url: 'https://www.youtube.com/watch?v=os-concepts' },
      { title: 'Computer Networks Fundamentals', url: 'https://www.youtube.com/watch?v=computer-networks' },
      { title: 'DevOps Engineering Guide', url: 'https://www.youtube.com/watch?v=devops-guide' },
      { title: 'Blockchain Technology and Crypto', url: 'https://www.youtube.com/watch?v=blockchain-crypto' },
      { title: 'Game Development Career', url: 'https://www.youtube.com/watch?v=game-development' },
      { title: 'Software Testing and QA', url: 'https://www.youtube.com/watch?v=software-testing' },
      { title: 'Enterprise Software Development', url: 'https://www.youtube.com/watch?v=enterprise-software' },
      { title: 'Embedded Systems Programming', url: 'https://www.youtube.com/watch?v=embedded-systems' },
      { title: 'Big Data and Hadoop Technologies', url: 'https://www.youtube.com/watch?v=big-data-hadoop' },
      { title: 'Natural Language Processing (NLP)', url: 'https://www.youtube.com/watch?v=nlp-nlp' },
      { title: 'Computer Vision and Image Processing', url: 'https://www.youtube.com/watch?v=computer-vision' },
    ],
  },

  'B.Tech - Electronics and Communication (ECE)': {
    websiteGuide: 'https://www.shiksha.com/engineering/ece-branch',
    relatedVideos: [
      { title: 'ECE Engineering - Overview and Scope', url: 'https://www.youtube.com/watch?v=ece-overview' },
      { title: 'Semiconductor and Microprocessor Technology', url: 'https://www.youtube.com/watch?v=semiconductor' },
      { title: 'Signal Processing Fundamentals', url: 'https://www.youtube.com/watch?v=signal-processing' },
      { title: 'VLSI Design and Fabrication', url: 'https://www.youtube.com/watch?v=vlsi-design' },
      { title: 'Telecommunication Systems', url: 'https://www.youtube.com/watch?v=telecom-systems' },
      { title: '5G Technology and Future', url: 'https://www.youtube.com/watch?v=5g-technology' },
      { title: 'Power Electronics Applications', url: 'https://www.youtube.com/watch?v=power-electronics' },
      { title: 'IoT - Internet of Things', url: 'https://www.youtube.com/watch?v=iot-technology' },
      { title: 'Antenna Design and Wireless Systems', url: 'https://www.youtube.com/watch?v=antenna-design' },
      { title: 'Microwave Engineering', url: 'https://www.youtube.com/watch?v=microwave-eng' },
      { title: 'Digital Signal Processing (DSP)', url: 'https://www.youtube.com/watch?v=dsp-digital' },
      { title: 'FPGA Programming and Applications', url: 'https://www.youtube.com/watch?v=fpga-programming' },
      { title: 'Analog and Digital Electronics', url: 'https://www.youtube.com/watch?v=analog-digital' },
      { title: 'Renewable Energy Systems', url: 'https://www.youtube.com/watch?v=renewable-energy' },
      { title: 'ECE Placements and Top Companies', url: 'https://www.youtube.com/watch?v=ece-placements' },
      { title: 'Robotics and Control Systems', url: 'https://www.youtube.com/watch?v=robotics-control' },
      { title: 'Satellite Communication Systems', url: 'https://www.youtube.com/watch?v=satellite-comm' },
      { title: 'Biomedical Signal Processing', url: 'https://www.youtube.com/watch?v=biomedical-signals' },
      { title: 'Smart Grid and Power Systems', url: 'https://www.youtube.com/watch?v=smart-grid' },
      { title: 'Nanotechnology in Electronics', url: 'https://www.youtube.com/watch?v=nano-electronics' },
    ],
  },

  'B.Tech - Mechanical Engineering': {
    websiteGuide: 'https://www.shiksha.com/engineering/mechanical-branch',
    relatedVideos: [
      { title: 'Mechanical Engineering - Scope and Career', url: 'https://www.youtube.com/watch?v=me-scope' },
      { title: 'Thermodynamics and Heat Transfer', url: 'https://www.youtube.com/watch?v=thermodynamics' },
      { title: 'Fluid Mechanics Applications', url: 'https://www.youtube.com/watch?v=fluid-mechanics' },
      { title: 'Machine Design and Components', url: 'https://www.youtube.com/watch?v=machine-design' },
      { title: 'CAD and CAM Technology', url: 'https://www.youtube.com/watch?v=cad-cam' },
      { title: 'Manufacturing Processes and Techniques', url: 'https://www.youtube.com/watch?v=manufacturing' },
      { title: 'Automobile Engineering Career', url: 'https://www.youtube.com/watch?v=automobile-eng' },
      { title: 'Aerospace Engineering Path', url: 'https://www.youtube.com/watch?v=aerospace-eng' },
      { title: 'Power Generation and Energy Systems', url: 'https://www.youtube.com/watch?v=power-generation' },
      { title: 'Renewable Energy Engineering', url: 'https://www.youtube.com/watch?v=renewable-me' },
      { title: 'Refrigeration and Air Conditioning', url: 'https://www.youtube.com/watch?v=refrigeration-ac' },
      { title: 'Hydraulics and Pneumatics Systems', url: 'https://www.youtube.com/watch?v=hydraulics' },
      { title: 'Vibrations and Control Systems', url: 'https://www.youtube.com/watch?v=vibrations' },
      { title: 'Materials Science and Engineering', url: 'https://www.youtube.com/watch?v=materials-science' },
      { title: 'Robotics and Automation', url: 'https://www.youtube.com/watch?v=robotics-automation' },
      { title: 'Production Planning and Control', url: 'https://www.youtube.com/watch?v=production-control' },
      { title: 'Quality Management Systems', url: 'https://www.youtube.com/watch?v=quality-management' },
      { title: 'ME Placements and Companies', url: 'https://www.youtube.com/watch?v=me-placements' },
      { title: 'Additive Manufacturing (3D Printing)', url: 'https://www.youtube.com/watch?v=3d-printing' },
      { title: 'Supply Chain and Logistics', url: 'https://www.youtube.com/watch?v=supply-chain-me' },
    ],
  },

  'B.Tech - Civil Engineering': {
    websiteGuide: 'https://www.shiksha.com/engineering/civil-branch',
    relatedVideos: [
      { title: 'Civil Engineering - Overview', url: 'https://www.youtube.com/watch?v=ce-overview' },
      { title: 'Structural Analysis and Design', url: 'https://www.youtube.com/watch?v=structural-design' },
      { title: 'Concrete Technology and Durability', url: 'https://www.youtube.com/watch?v=concrete-tech' },
      { title: 'Steel Construction Methods', url: 'https://www.youtube.com/watch?v=steel-construction' },
      { title: 'Foundation Engineering', url: 'https://www.youtube.com/watch?v=foundation-eng' },
      { title: 'Geotechnical Engineering Basics', url: 'https://www.youtube.com/watch?v=geotechnical' },
      { title: 'Water Resources Management', url: 'https://www.youtube.com/watch?v=water-resources' },
      { title: 'Environmental Engineering and Pollution', url: 'https://www.youtube.com/watch?v=environmental-eng' },
      { title: 'Highways and Transportation Engineering', url: 'https://www.youtube.com/watch?v=highways-transport' },
      { title: 'Surveying and Mapping Technology', url: 'https://www.youtube.com/watch?v=surveying' },
      { title: 'Building Information Modeling (BIM)', url: 'https://www.youtube.com/watch?v=bim-modeling' },
      { title: 'Construction Management Techniques', url: 'https://www.youtube.com/watch?v=construction-mgmt' },
      { title: 'Earthquake Engineering and Disaster Safety', url: 'https://www.youtube.com/watch?v=earthquake-eng' },
      { title: 'Urban Planning and Development', url: 'https://www.youtube.com/watch?v=urban-planning-ce' },
      { title: 'Bridge Engineering and Design', url: 'https://www.youtube.com/watch?v=bridge-engineering' },
      { title: 'Smart Cities and Infrastructure', url: 'https://www.youtube.com/watch?v=smart-cities' },
      { title: 'Government Infrastructure Projects', url: 'https://www.youtube.com/watch?v=govt-projects' },
      { title: 'Railway and Metro Systems', url: 'https://www.youtube.com/watch?v=railway-metro' },
      { title: 'Coastal Engineering', url: 'https://www.youtube.com/watch?v=coastal-engineering' },
      { title: 'CE Placements and Top Companies', url: 'https://www.youtube.com/watch?v=ce-placements' },
    ],
  },

  'B.Tech - Electrical Engineering': {
    websiteGuide: 'https://www.shiksha.com/engineering/electrical-branch',
    relatedVideos: [
      { title: 'Electrical Engineering - Overview', url: 'https://www.youtube.com/watch?v=ee-overview' },
      { title: 'Power Systems and Generation', url: 'https://www.youtube.com/watch?v=power-systems' },
      { title: 'Transmission and Distribution Networks', url: 'https://www.youtube.com/watch?v=transmission' },
      { title: 'Circuit Theory and Analysis', url: 'https://www.youtube.com/watch?v=circuit-theory' },
      { title: 'Electrical Machines - Motors and Generators', url: 'https://www.youtube.com/watch?v=electrical-machines' },
      { title: 'Control Systems Engineering', url: 'https://www.youtube.com/watch?v=control-systems' },
      { title: 'Power Electronics Applications', url: 'https://www.youtube.com/watch?v=power-electronics-ee' },
      { title: 'Renewable Energy Integration', url: 'https://www.youtube.com/watch?v=renewable-integration' },
      { title: 'Smart Grids and Microgrids', url: 'https://www.youtube.com/watch?v=smart-grids' },
      { title: 'Power Quality and Harmonics', url: 'https://www.youtube.com/watch?v=power-quality' },
      { title: 'Electrical Safety Standards', url: 'https://www.youtube.com/watch?v=electrical-safety' },
      { title: 'High Voltage Engineering', url: 'https://www.youtube.com/watch?v=high-voltage' },
      { title: 'Illumination and Lighting Design', url: 'https://www.youtube.com/watch?v=lighting-design' },
      { title: 'Industrial Automation and PLCs', url: 'https://www.youtube.com/watch?v=industrial-automation' },
      { title: 'Energy Management Systems', url: 'https://www.youtube.com/watch?v=energy-management' },
      { title: 'Electrical Installations in Buildings', url: 'https://www.youtube.com/watch?v=building-installations' },
      { title: 'Substation Design and Operation', url: 'https://www.youtube.com/watch?v=substation' },
      { title: 'EE Placements and Industry', url: 'https://www.youtube.com/watch?v=ee-placements' },
      { title: 'Fault Analysis and Protection', url: 'https://www.youtube.com/watch?v=fault-analysis' },
      { title: 'Motor Control and Drives', url: 'https://www.youtube.com/watch?v=motor-control' },
    ],
  },

  'Bachelor of Arts (BA)': {
    websiteGuide: 'https://www.careerindia.com/ba-degree-scope',
    relatedVideos: [
      { title: 'BA Degree - Career Options After College', url: 'https://www.youtube.com/watch?v=ba-career-options' },
      { title: 'Higher Education After BA', url: 'https://www.youtube.com/watch?v=ba-higher-education' },
      { title: 'Government Jobs for BA Graduates', url: 'https://www.youtube.com/watch?v=ba-govt-jobs' },
      { title: 'Teaching Career After BA', url: 'https://www.youtube.com/watch?v=ba-teaching' },
      { title: 'Mass Communication and Journalism', url: 'https://www.youtube.com/watch?v=mass-comm-ba' },
      { title: 'Psychology BA Specialization', url: 'https://www.youtube.com/watch?v=psychology-ba' },
      { title: 'History and Culture Studies', url: 'https://www.youtube.com/watch?v=history-ba' },
      { title: 'English Literature Career', url: 'https://www.youtube.com/watch?v=english-lit-ba' },
      { title: 'Political Science and Governance', url: 'https://www.youtube.com/watch?v=polsci-ba' },
      { title: 'Geography BA Path', url: 'https://www.youtube.com/watch?v=geography-ba' },
      { title: 'Social Work After BA', url: 'https://www.youtube.com/watch?v=social-work-ba' },
      { title: 'Public Administration Career', url: 'https://www.youtube.com/watch?v=pub-admin-ba' },
      { title: 'Foreign Languages BA', url: 'https://www.youtube.com/watch?v=languages-ba' },
      { title: 'Economics BA Specialization', url: 'https://www.youtube.com/watch?v=economics-ba' },
      { title: 'Law After BA - LLB Entrance', url: 'https://www.youtube.com/watch?v=law-after-ba' },
      { title: 'Public Sector Banks Recruitment', url: 'https://www.youtube.com/watch?v=ba-banking' },
      { title: 'Corporate Jobs for BA Graduates', url: 'https://www.youtube.com/watch?v=ba-corporate' },
      { title: 'MBA After BA - Entrance Exams', url: 'https://www.youtube.com/watch?v=mba-after-ba' },
      { title: 'Civil Service (UPSC) IAS Path', url: 'https://www.youtube.com/watch?v=ias-ba' },
      { title: 'Research and Academia Path', url: 'https://www.youtube.com/watch?v=research-ba' },
    ],
  },

  'Bachelor of Commerce (B.Com)': {
    websiteGuide: 'https://www.careerindia.com/bachelor-commerce-career',
    relatedVideos: [
      { title: 'B.Com Career Options and Scope', url: 'https://www.youtube.com/watch?v=bcom-career-scope' },
      { title: 'CA Course After B.Com', url: 'https://www.youtube.com/watch?v=ca-after-bcom' },
      { title: 'CS Course After B.Com', url: 'https://www.youtube.com/watch?v=cs-after-bcom' },
      { title: 'Banking Sector Recruitment', url: 'https://www.youtube.com/watch?v=banking-bcom' },
      { title: 'Taxation and GST Career', url: 'https://www.youtube.com/watch?v=taxation-bcom' },
      { title: 'Financial Analysis and Investment', url: 'https://www.youtube.com/watch?v=financial-analysis-bcom' },
      { title: 'Audit and Assurance', url: 'https://www.youtube.com/watch?v=audit-bcom' },
      { title: 'Stock Market and Trading', url: 'https://www.youtube.com/watch?v=stock-market-bcom' },
      { title: 'Insurance Sector Careers', url: 'https://www.youtube.com/watch?v=insurance-bcom' },
      { title: 'Corporate Finance Path', url: 'https://www.youtube.com/watch?v=corporate-finance-bcom' },
      { title: 'Business Analytics Career', url: 'https://www.youtube.com/watch?v=analytics-bcom' },
      { title: 'Accounting Standards and Reporting', url: 'https://www.youtube.com/watch?v=accounting-bcom' },
      { title: 'Management Accounting', url: 'https://www.youtube.com/watch?v=mgmt-accounting' },
      { title: 'International Accounting Practices', url: 'https://www.youtube.com/watch?v=intl-accounting' },
      { title: 'MBA After B.Com', url: 'https://www.youtube.com/watch?v=mba-bcom' },
      { title: 'Government Jobs for B.Com', url: 'https://www.youtube.com/watch?v=govt-bcom' },
      { title: 'Teaching Commerce Subjects', url: 'https://www.youtube.com/watch?v=teaching-bcom' },
      { title: 'Entrepreneurship After B.Com', url: 'https://www.youtube.com/watch?v=entrepreneurship-bcom' },
      { title: 'Cost Management and Control', url: 'https://www.youtube.com/watch?v=cost-mgmt-bcom' },
      { title: 'Salary and Placement Statistics', url: 'https://www.youtube.com/watch?v=placement-bcom' },
    ],
  },

  'Bachelor of Science (B.Sc)': {
    websiteGuide: 'https://www.careerindia.com/bsc-career-option',
    relatedVideos: [
      { title: 'B.Sc Degree - Career Opportunities', url: 'https://www.youtube.com/watch?v=bsc-career' },
      { title: 'Research Scientist Path', url: 'https://www.youtube.com/watch?v=research-bsc' },
      { title: 'Teaching Career After B.Sc', url: 'https://www.youtube.com/watch?v=teaching-bsc' },
      { title: 'Medical and Pharmacy Paths', url: 'https://www.youtube.com/watch?v=medical-bsc' },
      { title: 'Industrial and Applied Science', url: 'https://www.youtube.com/watch?v=industrial-bsc' },
      { title: 'Environmental Science Career', url: 'https://www.youtube.com/watch?v=enviro-bsc' },
      { title: 'Laboratory Technician Jobs', url: 'https://www.youtube.com/watch?v=lab-tech-bsc' },
      { title: 'Microbiology and Biotechnology', url: 'https://www.youtube.com/watch?v=microbio-bsc' },
      { title: 'Analytical Chemistry Career', url: 'https://www.youtube.com/watch?v=analytical-chem' },
      { title: 'Physics Research Opportunities', url: 'https://www.youtube.com/watch?v=physics-research' },
      { title: 'Data Science After B.Sc', url: 'https://www.youtube.com/watch?v=data-science-bsc' },
      { title: 'Psychology B.Sc Path', url: 'https://www.youtube.com/watch?v=psych-bsc' },
      { title: 'Geology and Earth Sciences', url: 'https://www.youtube.com/watch?v=geology-bsc' },
      { title: 'Zoology and Wildlife', url: 'https://www.youtube.com/watch?v=zoology-bsc' },
      { title: 'Botany and Agriculture', url: 'https://www.youtube.com/watch?v=botany-agri' },
      { title: 'Nursing and Healthcare', url: 'https://www.youtube.com/watch?v=nursing-bsc' },
      { title: 'Government Jobs for B.Sc', url: 'https://www.youtube.com/watch?v=govt-bsc' },
      { title: 'MBA After B.Sc', url: 'https://www.youtube.com/watch?v=mba-bsc' },
      { title: 'Quality Control in Industries', url: 'https://www.youtube.com/watch?v=qc-bsc' },
      { title: 'Higher Education Scholarships', url: 'https://www.youtube.com/watch?v=scholarship-bsc' },
    ],
  },

  'Diploma in Mechanical Engineering': {
    websiteGuide: 'https://www.shiksha.com/polytechnic/mechanical-diploma',
    relatedVideos: [
      { title: 'Diploma vs B.Tech - Which to Choose', url: 'https://www.youtube.com/watch?v=diploma-vs-btech' },
      { title: 'Mechanical Diploma - Industry Readiness', url: 'https://www.youtube.com/watch?v=mechanical-diploma' },
      { title: 'Placement Opportunities in Diploma', url: 'https://www.youtube.com/watch?v=diploma-placement' },
      { title: 'Skilled Technician Jobs', url: 'https://www.youtube.com/watch?v=technician-jobs' },
      { title: 'Manufacturing Floor Supervisor', url: 'https://www.youtube.com/watch?v=supervisor-jobs' },
      { title: 'CNC Machine Operation', url: 'https://www.youtube.com/watch?v=cnc-operation' },
      { title: 'Welding and Fabrication', url: 'https://www.youtube.com/watch?v=welding-fab' },
      { title: 'Quality Assurance Technician', url: 'https://www.youtube.com/watch?v=qa-technician' },
      { title: 'Automobile Technician Career', url: 'https://www.youtube.com/watch?v=auto-technician' },
      { title: 'Aircraft Maintenance Technician', url: 'https://www.youtube.com/watch?v=aircraft-tech' },
      { title: 'HVAC Systems Technician', url: 'https://www.youtube.com/watch?v=hvac-tech' },
      { title: 'Plant Maintenance Specialist', url: 'https://www.youtube.com/watch?v=plant-maintenance' },
      { title: 'Upgrade to B.Tech After Diploma', url: 'https://www.youtube.com/watch?v=lateral-entry' },
      { title: 'Government Jobs for Diploma', url: 'https://www.youtube.com/watch?v=govt-diploma' },
      { title: 'Railway Apprenticeship Programs', url: 'https://www.youtube.com/watch?v=railway-apprentice' },
      { title: 'Defence Sector Opportunities', url: 'https://www.youtube.com/watch?v=defence-diploma' },
      { title: 'Entrepreneurship in Manufacturing', url: 'https://www.youtube.com/watch?v=entrepreneurship-diploma' },
      { title: 'Salary Range for Diploma Graduates', url: 'https://www.youtube.com/watch?v=salary-diploma' },
      { title: 'Top Companies Hiring Diploma', url: 'https://www.youtube.com/watch?v=companies-diploma' },
      { title: 'Further Certification Courses', url: 'https://www.youtube.com/watch?v=certifications-diploma' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // CAREERS AFTER GRADUATION
  // ════════════════════════════════════════════════════════════════════════

  'Software Engineer': {
    websiteGuide: 'https://www.geeksforgeeks.org/software-engineer-career-path',
    relatedVideos: [
      { title: 'Software Engineer Career Path - Complete Guide', url: 'https://www.youtube.com/watch?v=software-engineer-guide' },
      { title: 'Top Tech Companies Hiring Engineers', url: 'https://www.youtube.com/watch?v=tech-companies-hiring' },
      { title: 'Software Development Life Cycle (SDLC)', url: 'https://www.youtube.com/watch?v=sdlc-explained' },
      { title: 'FAANG Preparation - Interview Tips', url: 'https://www.youtube.com/watch?v=faang-prep' },
      { title: 'Salary Negotiation for Software Engineers', url: 'https://www.youtube.com/watch?v=salary-negotiation' },
      { title: 'Remote Work Opportunities in Tech', url: 'https://www.youtube.com/watch?v=remote-tech-jobs' },
      { title: 'Startup vs MNC - Career Choice', url: 'https://www.youtube.com/watch?v=startup-vs-mnc' },
      { title: 'System Design Interview Preparation', url: 'https://www.youtube.com/watch?v=system-design' },
      { title: 'Coding Interview - LeetCode Solutions', url: 'https://www.youtube.com/watch?v=coding-interview' },
      { title: 'Freelance Development Career', url: 'https://www.youtube.com/watch?v=freelance-dev' },
      { title: 'Enterprise Software Development', url: 'https://www.youtube.com/watch?v=enterprise-dev' },
      { title: 'SaaS Product Development', url: 'https://www.youtube.com/watch?v=saas-dev' },
      { title: 'Tech Skills to Learn in 2024', url: 'https://www.youtube.com/watch?v=tech-skills-2024' },
      { title: 'Software Engineer Leadership Path', url: 'https://www.youtube.com/watch?v=tech-leadership' },
      { title: 'Work-Life Balance in Tech Industry', url: 'https://www.youtube.com/watch?v=work-life-balance-tech' },
      { title: 'Continuous Learning and Growth', url: 'https://www.youtube.com/watch?v=learning-growth' },
      { title: 'Diversity in Tech Careers', url: 'https://www.youtube.com/watch?v=diversity-tech' },
      { title: 'Burnout Prevention for Engineers', url: 'https://www.youtube.com/watch?v=burnout-prevention' },
      { title: 'Career Growth After Senior Engineer', url: 'https://www.youtube.com/watch?v=senior-eng-growth' },
      { title: 'Job Search Strategy for Engineers', url: 'https://www.youtube.com/watch?v=job-search-engineers' },
    ],
  },

  'Data Scientist': {
    websiteGuide: 'https://www.datasciencecentral.com/data-scientist-career',
    relatedVideos: [
      { title: 'Data Scientist Career - Complete Overview', url: 'https://www.youtube.com/watch?v=data-scientist-overview' },
      { title: 'Data Science vs Machine Learning', url: 'https://www.youtube.com/watch?v=ds-vs-ml' },
      { title: 'Data Analysis Tools and Techniques', url: 'https://www.youtube.com/watch?v=data-analysis-tools' },
      { title: 'Python for Data Science', url: 'https://www.youtube.com/watch?v=python-data-science' },
      { title: 'Statistical Methods in Data Science', url: 'https://www.youtube.com/watch?v=statistics-ds' },
      { title: 'Big Data Technologies - Hadoop and Spark', url: 'https://www.youtube.com/watch?v=big-data-tech' },
      { title: 'Machine Learning Algorithms Explained', url: 'https://www.youtube.com/watch?v=ml-algorithms' },
      { title: 'Deep Learning and Neural Networks', url: 'https://www.youtube.com/watch?v=deep-learning' },
      { title: 'Data Visualization Best Practices', url: 'https://www.youtube.com/watch?v=data-visualization' },
      { title: 'Business Analytics and KPIs', url: 'https://www.youtube.com/watch?v=business-analytics' },
      { title: 'Real-Time Data Processing', url: 'https://www.youtube.com/watch?v=realtime-data' },
      { title: 'Feature Engineering Techniques', url: 'https://www.youtube.com/watch?v=feature-engineering' },
      { title: 'Model Evaluation and Validation', url: 'https://www.youtube.com/watch?v=model-eval' },
      { title: 'Ethics in Data Science', url: 'https://www.youtube.com/watch?v=ethics-ds' },
      { title: 'Data Science Salary and Trends', url: 'https://www.youtube.com/watch?v=ds-salary' },
      { title: 'Top Companies Hiring Data Scientists', url: 'https://www.youtube.com/watch?v=ds-companies' },
      { title: 'Data Science Portfolio Projects', url: 'https://www.youtube.com/watch?v=ds-portfolio' },
      { title: 'Interview Preparation for Data Science', url: 'https://www.youtube.com/watch?v=ds-interview' },
      { title: 'Remote Data Science Jobs', url: 'https://www.youtube.com/watch?v=remote-ds' },
      { title: 'Advanced Analytics and Predictive Modeling', url: 'https://www.youtube.com/watch?v=predictive-modeling' },
    ],
  },

  'Product Manager': {
    websiteGuide: 'https://www.productschool.com/product-manager-career',
    relatedVideos: [
      { title: 'Product Manager Role - Complete Guide', url: 'https://www.youtube.com/watch?v=pm-guide' },
      { title: 'Transition to Product Management', url: 'https://www.youtube.com/watch?v=transition-pm' },
      { title: 'Product Strategy and Roadmap', url: 'https://www.youtube.com/watch?v=product-strategy' },
      { title: 'User Research and Discovery', url: 'https://www.youtube.com/watch?v=user-research' },
      { title: 'Agile and Scrum for Product Managers', url: 'https://www.youtube.com/watch?v=agile-scrum-pm' },
      { title: 'Product Analytics and Metrics', url: 'https://www.youtube.com/watch?v=product-analytics' },
      { title: 'A/B Testing and Experimentation', url: 'https://www.youtube.com/watch?v=ab-testing' },
      { title: 'Stakeholder Management', url: 'https://www.youtube.com/watch?v=stakeholder-mgmt' },
      { title: 'Product Launch Planning', url: 'https://www.youtube.com/watch?v=product-launch' },
      { title: 'Competitive Analysis', url: 'https://www.youtube.com/watch?v=competitive-analysis' },
      { title: 'Pricing Strategy for Products', url: 'https://www.youtube.com/watch?v=pricing-strategy' },
      { title: 'Go-to-Market Strategy', url: 'https://www.youtube.com/watch?v=gtm-strategy' },
      { title: 'Product Manager Interview Prep', url: 'https://www.youtube.com/watch?v=pm-interview' },
      { title: 'PM Skills and Competencies', url: 'https://www.youtube.com/watch?v=pm-skills' },
      { title: 'Technical PM vs Product Manager', url: 'https://www.youtube.com/watch?v=technical-pm' },
      { title: 'Remote Product Management', url: 'https://www.youtube.com/watch?v=remote-pm' },
      { title: 'Product Management Salary', url: 'https://www.youtube.com/watch?v=pm-salary' },
      { title: 'B2B vs B2C Product Management', url: 'https://www.youtube.com/watch?v=b2b-vs-b2c-pm' },
      { title: 'SaaS Product Management', url: 'https://www.youtube.com/watch?v=saas-pm' },
      { title: 'Startup Product Management', url: 'https://www.youtube.com/watch?v=startup-pm' },
    ],
  },

  'UX Designer': {
    websiteGuide: 'https://www.nngroup.com/careers/ux-designer',
    relatedVideos: [
      { title: 'UX Design Career Path', url: 'https://www.youtube.com/watch?v=ux-design-career' },
      { title: 'User Experience Principles', url: 'https://www.youtube.com/watch?v=ux-principles' },
      { title: 'UI vs UX - Clear Distinction', url: 'https://www.youtube.com/watch?v=ui-vs-ux' },
      { title: 'Design Thinking Methodology', url: 'https://www.youtube.com/watch?v=design-thinking' },
      { title: 'User Research and Personas', url: 'https://www.youtube.com/watch?v=user-personas' },
      { title: 'Wireframing and Prototyping', url: 'https://www.youtube.com/watch?v=wireframing' },
      { title: 'Usability Testing Methods', url: 'https://www.youtube.com/watch?v=usability-testing' },
      { title: 'Figma Design Tool Mastery', url: 'https://www.youtube.com/watch?v=figma-tutorial' },
      { title: 'Adobe XD vs Sketch vs Figma', url: 'https://www.youtube.com/watch?v=design-tools' },
      { title: 'Accessibility in UX Design', url: 'https://www.youtube.com/watch?v=accessibility-ux' },
      { title: 'Mobile App UX Design', url: 'https://www.youtube.com/watch?v=mobile-ux' },
      { title: 'Web UX Design Best Practices', url: 'https://www.youtube.com/watch?v=web-ux' },
      { title: 'Color Theory and Typography', url: 'https://www.youtube.com/watch?v=color-theory' },
      { title: 'UX Portfolio Building', url: 'https://www.youtube.com/watch?v=ux-portfolio' },
      { title: 'UX Designer Interview Preparation', url: 'https://www.youtube.com/watch?v=ux-interview' },
      { title: 'UX Design Salary and Market', url: 'https://www.youtube.com/watch?v=ux-salary' },
      { title: 'Remote UX Design Jobs', url: 'https://www.youtube.com/watch?v=remote-ux' },
      { title: 'Interaction Design Concepts', url: 'https://www.youtube.com/watch?v=interaction-design' },
      { title: 'Information Architecture', url: 'https://www.youtube.com/watch?v=information-arch' },
      { title: 'UX Analytics and Metrics', url: 'https://www.youtube.com/watch?v=ux-analytics' },
    ],
  },

  'Business Analyst': {
    websiteGuide: 'https://www.indeed.com/career-advice/finding-a-job/how-to-become-business-analyst',
    relatedVideos: [
      { title: 'Business Analyst Career Overview', url: 'https://www.youtube.com/watch?v=ba-career-overview' },
      { title: 'Business Analysis Fundamentals', url: 'https://www.youtube.com/watch?v=ba-fundamentals' },
      { title: 'Requirements Gathering Techniques', url: 'https://www.youtube.com/watch?v=requirements-gathering' },
      { title: 'Use Cases and User Stories', url: 'https://www.youtube.com/watch?v=use-cases' },
      { title: 'Data Analysis for Business', url: 'https://www.youtube.com/watch?v=data-analysis-ba' },
      { title: 'Business Process Improvement', url: 'https://www.youtube.com/watch?v=process-improvement' },
      { title: 'SQL for Business Analysts', url: 'https://www.youtube.com/watch?v=sql-ba' },
      { title: 'Excel Advanced Skills', url: 'https://www.youtube.com/watch?v=excel-advanced' },
      { title: 'Tableau and Power BI', url: 'https://www.youtube.com/watch?v=tableau-powerbi' },
      { title: 'Business Requirements Document (BRD)', url: 'https://www.youtube.com/watch?v=brd-creation' },
      { title: 'Stakeholder Communication', url: 'https://www.youtube.com/watch?v=stakeholder-comm' },
      { title: 'Agile Business Analysis', url: 'https://www.youtube.com/watch?v=agile-ba' },
      { title: 'Root Cause Analysis', url: 'https://www.youtube.com/watch?v=root-cause-analysis' },
      { title: 'Business Analyst Salary', url: 'https://www.youtube.com/watch?v=ba-salary' },
      { title: 'Top Companies for Business Analysts', url: 'https://www.youtube.com/watch?v=ba-companies' },
      { title: 'BA Interview Preparation', url: 'https://www.youtube.com/watch?v=ba-interview' },
      { title: 'Business Analyst Tools and Software', url: 'https://www.youtube.com/watch?v=ba-tools' },
      { title: 'Career Growth as Business Analyst', url: 'https://www.youtube.com/watch?v=ba-growth' },
      { title: 'Remote BA Jobs', url: 'https://www.youtube.com/watch?v=remote-ba' },
      { title: 'Industry-Specific BA Roles', url: 'https://www.youtube.com/watch?v=industry-ba' },
    ],
  },

  'Management Consultant': {
    websiteGuide: 'https://www.mckinsey.com/careers/career-paths',
    relatedVideos: [
      { title: 'Management Consultant Career Path', url: 'https://www.youtube.com/watch?v=mc-career-path' },
      { title: 'Top Consulting Firms - McKinsey, BCG, Bain', url: 'https://www.youtube.com/watch?v=top-consulting' },
      { title: 'Case Interview Preparation', url: 'https://www.youtube.com/watch?v=case-interview' },
      { title: 'Consulting Frameworks Explained', url: 'https://www.youtube.com/watch?v=consulting-frameworks' },
      { title: 'Market Research and Analysis', url: 'https://www.youtube.com/watch?v=market-research' },
      { title: 'Business Strategy Development', url: 'https://www.youtube.com/watch?v=business-strategy' },
      { title: 'Organization and Change Management', url: 'https://www.youtube.com/watch?v=change-management' },
      { title: 'Financial Modeling and Analysis', url: 'https://www.youtube.com/watch?v=financial-modeling' },
      { title: 'Client Relationship Management', url: 'https://www.youtube.com/watch?v=client-management' },
      { title: 'PowerPoint Presentation Skills', url: 'https://www.youtube.com/watch?v=powerpoint-skills' },
      { title: 'Management Consulting Salary', url: 'https://www.youtube.com/watch?v=consulting-salary' },
      { title: 'Work-Life Balance in Consulting', url: 'https://www.youtube.com/watch?v=consulting-wlb' },
      { title: 'Strategic Planning Process', url: 'https://www.youtube.com/watch?v=strategic-planning' },
      { title: 'Operations Consulting', url: 'https://www.youtube.com/watch?v=operations-consulting' },
      { title: 'Digital Transformation Consulting', url: 'https://www.youtube.com/watch?v=digital-consulting' },
      { title: 'Sustainability Consulting', url: 'https://www.youtube.com/watch?v=sustainability-consulting' },
      { title: 'Consultant CV and Resume Tips', url: 'https://www.youtube.com/watch?v=consultant-resume' },
      { title: 'Transition to Consulting', url: 'https://www.youtube.com/watch?v=transition-consulting' },
      { title: 'Independent Consultant or Freelance', url: 'https://www.youtube.com/watch?v=freelance-consulting' },
      { title: 'Consulting Exit Opportunities', url: 'https://www.youtube.com/watch?v=consulting-exit' },
    ],
  },
}

// Helper function to get data for a specific career
export function getCareerVideoWebsite(careerName: string): CareerVideoWebsite | null {
  return CAREER_VIDEOS_AND_WEBSITES[careerName] || null
}

// Helper function to get all available careers
export function getAllCareersWithVideos(): string[] {
  return Object.keys(CAREER_VIDEOS_AND_WEBSITES)
}

// Helper function to get videos for a specific career
export function getCareerVideos(careerName: string): Array<{ title: string; url: string }> {
  const data = CAREER_VIDEOS_AND_WEBSITES[careerName]
  return data ? data.relatedVideos : []
}

// Helper function to get website for a specific career
export function getCareerWebsite(careerName: string): string {
  const data = CAREER_VIDEOS_AND_WEBSITES[careerName]
  return data ? data.websiteGuide : 'https://www.shiksha.com/careers'
}
